apiVersion: v1
data:
  mykey: myvalue
  key1: val1
  key2: val2
kind: ConfigMap
metadata:
  name: cm1
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
#     - name: CMFirstVariable
#       valueFrom:
#          configMapKeyRef:
#              name: cm1
#              key: key1
    envFrom:
      - configMapRef:
            name: cm1  
  restartPolicy: Always
