apiVersion: apps/v1
kind: ReplicaSet
metadata:
   labels:
      name: nginx
   name: myfirstreplicaset
   namespace: default  
spec:  
  replicas: 2
  selector: 
    matchLabels:
        run: nginx
        owner: nitin   
  template:
    metadata:
      labels:
        run: nginx
        secondary: nitin
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
